In [1]:
import numpy as np

In [2]:
# create list x
x = [[1,3,5],[7,9,0]]

In [6]:
# convert list x as numpy array1
arr1 = np.array(x)
arr1

array([[1, 3, 5],
       [7, 9, 0]])

In [4]:
# create list y
y = [[11,13,15],[17,19,10]]

In [7]:
arr2 = np.array(y)
arr2

array([[11, 13, 15],
       [17, 19, 10]])

In [8]:
# Concatenate arr1 and arr2 using tuple
# row wise concatenate
np.concatenate((arr1,arr2), axis = 0)

array([[ 1,  3,  5],
       [ 7,  9,  0],
       [11, 13, 15],
       [17, 19, 10]])

In [9]:
# Concatenate arr1 and arr2 using tuple
# column wise concatenate
np.concatenate((arr1,arr2), axis = 1)

array([[ 1,  3,  5, 11, 13, 15],
       [ 7,  9,  0, 17, 19, 10]])

In [11]:
# Concatenate arr1 and arr2 using tuple
# row wise concatenate
np.vstack((arr1,arr2))

array([[ 1,  3,  5],
       [ 7,  9,  0],
       [11, 13, 15],
       [17, 19, 10]])

In [13]:
# Concatenate arr1 and arr2 using tuple
# column wise concatenate
np.hstack((arr1,arr2))

array([[ 1,  3,  5, 11, 13, 15],
       [ 7,  9,  0, 17, 19, 10]])