In [1]:
import numpy as np

In [2]:
# create list
x = [1,4,5,6,7,8,1,4]

In [3]:
# convert list in array
d = np.array(x)

In [5]:
# d is array
# in list we pass the positions (2,5) at which we want to split the array
np.split(d,[2,5])

[array([1, 4]), array([5, 6, 7]), array([8, 1, 4])]

In [6]:
# d is array
# in list we pass the positions (3,6) at which we want to split the array
np.split(d,[3,6])

[array([1, 4, 5]), array([6, 7, 8]), array([1, 4])]

In [7]:
# d is array
# in list we pass the positions (2,6) at which we want to split the array
np.split(d,[2,6])

[array([1, 4]), array([5, 6, 7, 8]), array([1, 4])]

In [8]:
# d is array
# in list we pass the positions (2,4,6) at which we want to split the array
np.split(d,[2,4,6])

[array([1, 4]), array([5, 6]), array([7, 8]), array([1, 4])]

In [9]:
# d is array
# in list we pass the positions (1,3,5,7) at which we want to split the array
np.split(d,[1,3,5,7])

[array([1]), array([4, 5]), array([6, 7]), array([8, 1]), array([4])]

In [10]:
# create list
x = [[1,4,5,6,7,8,1,4],
     [11,14,15,16,17,18,11,14]]

In [11]:
d = np.array(x)
d

array([[ 1,  4,  5,  6,  7,  8,  1,  4],
       [11, 14, 15, 16, 17, 18, 11, 14]])

In [12]:
# column wise split because using axis = 1
np.split(d,[4,6], axis = 1)

[array([[ 1,  4,  5,  6],
        [11, 14, 15, 16]]),
 array([[ 7,  8],
        [17, 18]]),
 array([[ 1,  4],
        [11, 14]])]

In [16]:
# column wise split because using axis = 1
np.split(d,[3,6,7], axis = 1)

[array([[ 1,  4,  5],
        [11, 14, 15]]),
 array([[ 6,  7,  8],
        [16, 17, 18]]),
 array([[ 1],
        [11]]),
 array([[ 4],
        [14]])]

In [13]:
# row wise split because using axis = 0
np.split(d,[4,6], axis = 0)

[array([[ 1,  4,  5,  6,  7,  8,  1,  4],
        [11, 14, 15, 16, 17, 18, 11, 14]]),
 array([], shape=(0, 8), dtype=int32),
 array([], shape=(0, 8), dtype=int32)]

In [17]:
# row wise split because using axis = 0
np.split(d,[2,4,6], axis = 0)

[array([[ 1,  4,  5,  6,  7,  8,  1,  4],
        [11, 14, 15, 16, 17, 18, 11, 14]]),
 array([], shape=(0, 8), dtype=int32),
 array([], shape=(0, 8), dtype=int32),
 array([], shape=(0, 8), dtype=int32)]

In [18]:
# row wise split because using axis = 0
np.split(d,[1], axis = 0)

[array([[1, 4, 5, 6, 7, 8, 1, 4]]), array([[11, 14, 15, 16, 17, 18, 11, 14]])]

In [21]:
# create list
y = [[1,4,5,6,7,8,1,4],[21,24,25,26,27,28,21,24],[[31,34,35,36,37,38,31,34],[11,14,15,16,17,18,11,14]]]

In [22]:
e = np.array(y)
e

array([list([1, 4, 5, 6, 7, 8, 1, 4]),
       list([21, 24, 25, 26, 27, 28, 21, 24]),
       list([[31, 34, 35, 36, 37, 38, 31, 34], [11, 14, 15, 16, 17, 18, 11, 14]])],
      dtype=object)

In [23]:
# row wise split because using axis = 0
np.split(d,[1], axis = 0)

[array([[1, 4, 5, 6, 7, 8, 1, 4]]), array([[11, 14, 15, 16, 17, 18, 11, 14]])]

In [24]:
# row wise split because using axis = 0
np.split(d,[3,5,7], axis = 0)

[array([[ 1,  4,  5,  6,  7,  8,  1,  4],
        [11, 14, 15, 16, 17, 18, 11, 14]]),
 array([], shape=(0, 8), dtype=int32),
 array([], shape=(0, 8), dtype=int32),
 array([], shape=(0, 8), dtype=int32)]

In [25]:
# row wise split because using vsplit
np.vsplit(d,[1])

[array([[1, 4, 5, 6, 7, 8, 1, 4]]), array([[11, 14, 15, 16, 17, 18, 11, 14]])]

In [26]:
# column wise split because using hsplit
np.hsplit(d,[1])

[array([[ 1],
        [11]]),
 array([[ 4,  5,  6,  7,  8,  1,  4],
        [14, 15, 16, 17, 18, 11, 14]])]

In [28]:
# column wise split because using hsplit
np.hsplit(d,[2,5,7])

[array([[ 1,  4],
        [11, 14]]),
 array([[ 5,  6,  7],
        [15, 16, 17]]),
 array([[ 8,  1],
        [18, 11]]),
 array([[ 4],
        [14]])]

In [29]:
# column wise split because using hsplit
np.hsplit(d,[2,5,8])

[array([[ 1,  4],
        [11, 14]]),
 array([[ 5,  6,  7],
        [15, 16, 17]]),
 array([[ 8,  1,  4],
        [18, 11, 14]]),
 array([], shape=(2, 0), dtype=int32)]