In [1]:
import numpy as np

In [2]:
a = np.random.rand((10))

In [3]:
b = np.random.rand((10))

In [4]:
a

array([0.4781224 , 0.53475067, 0.9610042 , 0.41818153, 0.03614   ,
       0.18059684, 0.71148005, 0.38623677, 0.25635464, 0.45403465])

In [5]:
b

array([0.22881549, 0.2156165 , 0.5111731 , 0.88562376, 0.53989343,
       0.50827438, 0.7311457 , 0.82236123, 0.96463647, 0.91999542])

In [6]:
a + b

array([0.70693789, 0.75036717, 1.4721773 , 1.30380529, 0.57603343,
       0.68887123, 1.44262575, 1.208598  , 1.22099111, 1.37403007])

In [7]:
a - b

array([ 0.24930691,  0.31913417,  0.44983109, -0.46744223, -0.50375343,
       -0.32767754, -0.01966565, -0.43612446, -0.70828184, -0.46596078])

In [8]:
a * b

array([0.10940181, 0.11530107, 0.4912395 , 0.3703515 , 0.01951175,
       0.09179275, 0.52019558, 0.31762614, 0.24728903, 0.41770979])

In [9]:
a / b

array([2.08955431, 2.4801009 , 1.87999758, 0.4721887 , 0.06693914,
       0.35531369, 0.97310296, 0.46966802, 0.26575258, 0.49351838])

In [10]:
2 * a

array([0.9562448 , 1.06950135, 1.9220084 , 0.83636306, 0.07228   ,
       0.36119369, 1.4229601 , 0.77247354, 0.51270927, 0.90806929])

In [11]:
1 / a

array([ 2.09151464,  1.87003037,  1.04057818,  2.391306  , 27.67017119,
        5.53719531,  1.40552079,  2.58908545,  3.90084617,  2.2024751 ])

In [12]:
2 * b

array([0.45763099, 0.431233  , 1.02234621, 1.77124752, 1.07978686,
       1.01654876, 1.46229141, 1.64472246, 1.92927295, 1.83999084])

In [13]:
1 / b

array([4.37033343, 4.63786402, 1.95628446, 1.12914767, 1.85221739,
       1.96744128, 1.36771644, 1.21601063, 1.03665995, 1.08696193])

In [14]:
a > 0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [15]:
a[a>0]

array([0.4781224 , 0.53475067, 0.9610042 , 0.41818153, 0.03614   ,
       0.18059684, 0.71148005, 0.38623677, 0.25635464, 0.45403465])

In [16]:
b > 0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [17]:
b[b>0]

array([0.22881549, 0.2156165 , 0.5111731 , 0.88562376, 0.53989343,
       0.50827438, 0.7311457 , 0.82236123, 0.96463647, 0.91999542])