In [1]:
import numpy as np

In [2]:
# create numpy array
x = np.array([10,9,7,10,7])

In [3]:
# find mean of given array
x.mean()

8.6

In [4]:
# find cumelative sum of given array
x.cumsum()

array([10, 19, 26, 36, 43], dtype=int32)

In [5]:
# find cumelative product of given array
x.cumprod()

array([   10,    90,   630,  6300, 44100], dtype=int32)

In [7]:
# find those element that greater than 6 of given array
y = x>6
y

array([ True,  True,  True,  True,  True])

In [8]:
# find total true element of given array
y.sum()

5

In [9]:
# find any true element of given array
y.any()

True

In [10]:
# find all elements true or not of given array
y.all()

True

In [11]:
# find those element that greater than 7 of given array
y = x>7
y

array([ True,  True, False,  True, False])

In [12]:
# find total true element of given array
y.sum()

3

In [13]:
# find any true element of given array
y.any()

True

In [14]:
# find all elements true or not of given array
y.all()

False

In [15]:
x

array([10,  9,  7, 10,  7])

In [18]:
# sorting by given array x
x.sort()
x

array([ 7,  7,  9, 10, 10])

In [17]:
# find unique elements of given array
np.unique(x)

array([ 7,  9, 10])