In [1]:
import numpy as np

In [2]:
# create Array
x = np.array([10,9,8,6,11])

In [3]:
# find square root
np.sqrt(x)

array([3.16227766, 3.        , 2.82842712, 2.44948974, 3.31662479])

In [4]:
# find power
np.power(x,2)

array([100,  81,  64,  36, 121], dtype=int32)

In [5]:
y = [7,1,2,3,-1]

In [6]:
# find maximum value to compare array x and y
np.maximum(x,y)

array([10,  9,  8,  6, 11])

In [7]:
# find minimum value to compare array x and y
np.minimum(x,y)

array([ 7,  1,  2,  3, -1])

In [8]:
np.max(x)

11

In [9]:
np.max(y)

7