In [1]:
import  numpy as np

In [2]:
# create 3 by 2 matrix
x = np.random.rand(3,2)

In [3]:
# create 2 by 3 matrix
y = np.random.rand(2,3)

In [4]:
# find dot product of matrix x,y
x.dot(y)

array([[0.64009826, 0.24800382, 0.25392767],
       [0.61907209, 0.23795503, 0.46505073],
       [0.64568432, 0.24865881, 0.43027124]])

In [7]:
# find dot product of matrix y,x
y.dot(x)

array([[0.60329251, 0.66088558],
       [0.49683817, 0.70503202]])

In [5]:
# find tranpose of matrix x
x.transpose()

array([[0.61782877, 0.25824121, 0.35401822],
       [0.35560771, 0.91130637, 0.80888235]])

In [6]:
# find tranpose of matrix y
y.transpose()

array([[0.77075509, 0.46091126],
       [0.30006197, 0.17608421],
       [0.14013255, 0.47060214]])

In [8]:
# trace of matrix x
x.trace()

1.5291351389456052

In [14]:
# trace of matrix y
y.trace()

0.9468392916066612