In [1]:
import numpy as np

In [2]:
np.sum([1,3])

4

In [3]:
np.__version__

'1.18.2'

In [1]:
pip install --upgrade numpy

  Using cached numpy-1.18.2-cp37-cp37m-win_amd64.whl (12.8 MB)
  Attempting uninstall: numpy
    Found existing installation: numpy 1.18.1
    Uninstalling numpy-1.18.1:
Note: you may need to restart the kernel to use updated packages.


ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'c:\\programdata\\anaconda3\\lib\\site-packages\\numpy\\compat\\py3k.py'
Consider using the `--user` option or check the permissions.



In [4]:
#  Magic Function ka start main % ka sign laga hoga
# %history
# %run abc.py
# %load abc.py

import numpy as np
np.sum([1,3])
np.__version__
#  Magic Function
%history


In [ ]:
%run abc.py
%load abc.py

In [5]:
# python function
%time list(range(2000000))[:20]

Wall time: 108 ms


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [6]:
# NumPy function
%time np.arange(2000000)

Wall time: 7.05 ms


array([      0,       1,       2, ..., 1999997, 1999998, 1999999])

In [7]:
# python function
%time [x+5 for x in range(1,1000000)][:20]

Wall time: 237 ms


[6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]

In [ ]:
l1 = list(range(1,100000))
for i, n in for list(enumerate(l))

In [12]:
# Python function
%time
l = list(range(1,100000))
l2 = list(enumerate(l))
for i, v in l2:
    l[i] = l[i] + 5
l[:20]

Wall time: 0 ns


[6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]

In [20]:
# Python function
a = np.array([[1,2,4],
              [3,5,6],
              [2,1,5]])
for r, rd in list(enumerate(a)):
    for c, cd in list(enumerate(rd)):
        print(c, cd)
        break
    break

0 1


In [22]:
# Python function
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print("Before adding 5")
print(a)
for r, rd in list(enumerate(a)):
    for c, cd in list(enumerate(rd)):
        a[r][c] = a[r][c] + 5
        
print("After adding 5")
print(a)

Before adding 5
[[1 2 3]
 [4 5 6]
 [7 8 9]]
After adding 5
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [23]:
# Numpy function
a = np.arange(1,10).reshape((3,3))
a = a+5
a

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [26]:
a = np.arange(1,31).reshape((3,5,2))
a = a + 5
a

array([[[ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25]],

       [[26, 27],
        [28, 29],
        [30, 31],
        [32, 33],
        [34, 35]]])

In [27]:
a = np.arange(1,28).reshape((3,3,3))
a = a + 5
a

array([[[ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32]]])

In [31]:
a = np.arange(1,28).reshape((3,3,3))
a = a - 5
a

array([[[-4, -3, -2],
        [-1,  0,  1],
        [ 2,  3,  4]],

       [[ 5,  6,  7],
        [ 8,  9, 10],
        [11, 12, 13]],

       [[14, 15, 16],
        [17, 18, 19],
        [20, 21, 22]]])

In [32]:
a = np.arange(1,28).reshape((3,3,3))
a = a * 5
a

array([[[  5,  10,  15],
        [ 20,  25,  30],
        [ 35,  40,  45]],

       [[ 50,  55,  60],
        [ 65,  70,  75],
        [ 80,  85,  90]],

       [[ 95, 100, 105],
        [110, 115, 120],
        [125, 130, 135]]])

In [33]:
a = np.arange(1,28).reshape((3,3,3))
a = a / 5
a

array([[[0.2, 0.4, 0.6],
        [0.8, 1. , 1.2],
        [1.4, 1.6, 1.8]],

       [[2. , 2.2, 2.4],
        [2.6, 2.8, 3. ],
        [3.2, 3.4, 3.6]],

       [[3.8, 4. , 4.2],
        [4.4, 4.6, 4.8],
        [5. , 5.2, 5.4]]])

In [34]:
a = np.arange(1,28).reshape((3,3,3))
a = a % 5
a

array([[[1, 2, 3],
        [4, 0, 1],
        [2, 3, 4]],

       [[0, 1, 2],
        [3, 4, 0],
        [1, 2, 3]],

       [[4, 0, 1],
        [2, 3, 4],
        [0, 1, 2]]], dtype=int32)

In [36]:
a = np.random.randn(2,3)
a

array([[-0.91459186,  0.54134585,  0.69698651],
       [ 0.20748762, -1.36036363,  0.68641217]])

In [37]:
a = np.random.randn(2,3,3)
a

array([[[-1.72089635,  1.38338328, -0.06305087],
        [ 0.15529508,  0.01970846,  1.82725276],
        [-0.07102567, -1.80747377, -0.71281557]],

       [[ 0.28921235,  0.87844095, -1.56193567],
        [ 0.03997193, -0.36340059,  1.0165623 ],
        [ 1.18115531,  0.80993576, -0.26490331]]])

In [38]:
a = np.random.randn(2,3,3,4)
a

array([[[[-0.63975582, -0.23460464,  1.48164908,  1.26414908],
         [-0.15329472, -0.00569703, -0.59810825,  0.00784218],
         [-0.86069566, -0.09517392, -0.26753844, -1.43591459]],

        [[-0.62411141, -0.17736907,  0.3840868 , -0.24784335],
         [ 0.24794165, -0.62049454,  1.17107128,  0.53267681],
         [ 0.00876042,  0.62007397, -1.84761854, -0.82665877]],

        [[-0.28527089, -0.93520619,  1.26623307,  0.41257177],
         [-0.07017355, -1.23148435,  0.01771993, -0.47743016],
         [-0.58149298,  0.1459901 , -2.68837339, -1.40756218]]],


       [[[-0.71495148, -0.9371089 ,  0.59909389,  0.01863536],
         [-0.69838516, -0.33885676,  0.45354763, -0.49771104],
         [ 1.00981316,  0.4490358 ,  0.08000506,  0.48283203]],

        [[ 0.11675411,  1.82091539,  1.08516268,  0.15904885],
         [ 0.37482342,  0.33331375,  0.00600829,  0.0506434 ],
         [ 1.02803062,  0.33377673, -0.53457027, -0.23701403]],

        [[ 1.30059687,  1.44372454,  0.1052

In [39]:
a = np.random.randn(2,3,3,4,5)
a

array([[[[[-1.97742480e-01, -1.66192550e+00, -7.75194927e-01,
            5.91338399e-01,  1.80630050e+00],
          [ 2.88707447e-01,  5.10050510e-01,  6.08671447e-01,
            1.04521247e-02,  1.81495298e+00],
          [ 8.99953093e-01,  2.37635644e-01,  1.20499951e+00,
           -6.64427079e-01,  1.54125940e+00],
          [ 2.27652138e+00,  9.16239529e-01, -9.23675944e-01,
           -1.30997315e+00, -1.77935144e+00]],

         [[-6.40171224e-01, -4.15957576e-01,  6.18204653e-02,
           -7.10335023e-02,  2.93061372e-01],
          [-1.19985443e-01, -9.83055270e-01, -1.93745022e+00,
            2.83405750e-01, -1.33997422e+00],
          [-1.11070790e-01,  2.32724545e+00,  6.58035173e-01,
           -2.17808990e-01,  9.78613688e-01],
          [ 1.50970392e+00,  1.27141610e+00,  2.94235770e+00,
           -2.03291680e-01, -1.13230633e+00]],

         [[ 2.17537052e+00, -4.85015510e-01, -1.21309259e+00,
           -7.79974652e-01, -1.22623874e+00],
          [ 8.74799583e-

In [40]:
a = np.random.randn(2,3,3,4,5,5)
a

array([[[[[[ 2.84603619e-01, -2.00019849e+00, -1.71293852e+00,
            -1.15706211e+00, -1.19941122e+00],
           [ 3.30455382e+00,  2.03885586e-01,  8.62722356e-01,
            -4.06084304e-01,  1.75134156e-01],
           [-1.75753382e+00,  1.61782855e+00, -2.40572244e-01,
             1.86146104e+00, -1.43110957e+00],
           [-1.21572135e+00, -5.98228862e-01, -1.07100502e-01,
             9.51865083e-01,  5.75952232e-01],
           [-8.32022913e-01,  3.70449826e-04, -1.01755761e+00,
             4.61293247e-01,  2.99657407e-01]],

          [[-3.90595948e-01, -8.53378992e-01,  3.53010950e-01,
            -1.74566729e+00,  2.62924638e-01],
           [-2.73148860e-01, -5.03680088e-01,  6.15385187e-01,
             1.53684097e+00, -3.76915477e-01],
           [ 2.35053972e+00,  1.10529671e-01,  1.21822746e+00,
            -5.95888656e-01,  7.62152591e-01],
           [-1.09885310e+00, -5.93462705e-01, -2.36331421e+00,
            -1.47337683e-01,  1.84142276e+00],
        

In [41]:
a = np.random.randn(2,3,3,4,5,5)
print(a.ndim)
print(a.shape)
a

6
(2, 3, 3, 4, 5, 5)


array([[[[[[ 4.71316244e-01,  2.04712831e+00, -1.44902121e+00,
             1.30738300e+00,  1.58622378e+00],
           [-3.95633423e-01,  2.00238789e-01, -3.49395230e-01,
            -1.59841939e+00, -1.85948762e-02],
           [ 5.95029446e-01,  1.67467122e+00,  3.66034506e-01,
             1.85297041e-01,  8.29375864e-01],
           [-3.37084611e-01, -2.02729357e-01, -4.27737449e-01,
            -1.06743825e+00,  2.37280986e-01],
           [-8.96651360e-02, -8.45868237e-01, -8.15331263e-01,
             1.07856813e+00,  1.00874985e+00]],

          [[ 4.30067791e-01,  4.45874187e-01,  4.80623573e-02,
            -2.57718008e-01,  7.73940829e-01],
           [-3.20463257e-01, -4.52742653e-02,  3.08688932e-02,
            -1.98392528e-01, -4.69256346e-02],
           [-9.88721939e-01,  6.54315909e-01,  3.40374652e-01,
            -4.05781087e-01,  3.75934727e-01],
           [ 1.16762234e+00,  1.58059318e-01, -8.28016138e-02,
             2.78492949e-02, -1.38837834e-01],
        

In [42]:
a = np.random.randn(2,3,3,4,5,5)
print(a.ndim)
print(a.shape)
a = a * 5
a

6
(2, 3, 3, 4, 5, 5)


array([[[[[[-5.27771776e-01,  2.69370025e+00,  3.25694729e+00,
            -2.92338910e+00,  2.48033740e+00],
           [-8.59430434e+00,  1.03093635e+00, -7.53690792e+00,
             4.83013597e+00,  7.12066373e+00],
           [-8.07946437e-01,  5.58498697e+00,  8.42210023e-01,
            -1.26751234e-01, -2.09591094e+00],
           [-6.36673526e+00,  2.79712258e+00,  1.99749664e+01,
             3.20025894e+00, -2.88116287e-01],
           [ 1.05846574e+00, -7.02327618e+00, -5.29872482e+00,
            -1.38924335e+01,  3.96205251e+00]],

          [[ 3.72170038e+00,  3.81269565e+00, -9.00147392e-01,
             5.97394548e-01,  1.66380120e+00],
           [-8.43217436e+00,  1.35360792e+01,  2.03016495e+00,
            -4.18866498e+00,  4.03826492e+00],
           [ 7.90312576e+00,  3.80406911e+00, -7.11462944e+00,
            -1.99146203e+00, -8.89036110e-01],
           [ 3.77451774e+00,  2.17753610e-02, -5.98067353e+00,
            -4.85046649e+00,  1.65244007e+00],
        

In [45]:
a = np.arange(1,13).reshape(6,2)
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [43]:
a = np.random.randn(2,6)
print(a)

print(a * a)

[[-0.15670294 -0.97956432 -0.23395967  1.04266348  1.58101934 -0.2340073 ]
 [-0.59516561  0.73198092  0.88791169 -0.41012591  0.12812993 -1.01001599]]
[[0.02455581 0.95954625 0.05473713 1.08714713 2.49962214 0.05475942]
 [0.3542221  0.53579607 0.78838717 0.16820326 0.01641728 1.02013229]]


In [44]:
a = np.random.randint(2,6)
print(a)

print(a * a)

5
25


<img src = "https://www.pythoninformer.com/img/numpy/3d-array.png">

# a[i,j,k]

In [28]:
a[2]

array([[24, 25, 26],
       [27, 28, 29],
       [30, 31, 32]])

In [29]:
a[2,0]

array([24, 25, 26])

In [30]:
a[2,0,1]

25

In [8]:
# NumPy function
%time np.arange(1,1000000) + 5

Wall time: 7.46 ms


array([      6,       7,       8, ..., 1000002, 1000003, 1000004])

In [13]:
l = np.arange(1,1000000)
l = l + 5
l

array([      6,       7,       8, ..., 1000002, 1000003, 1000004])

In [14]:
type(l)

numpy.ndarray

In [15]:
l.shape

(999999,)

In [16]:
#dimension
l.ndim

1

# Dimensions

In [18]:
a = np.array([1,2,4,5])
print(a)
print(a.ndim)
print(a.shape)
print(a.dtype)

[1 2 4 5]
1
(4,)
int32


In [19]:
a = np.array([[1,2,4],
              [3,5,6],
              [2,1,5]])
print(a)
print(a.ndim)
print(a.shape)
print(a.dtype)

[list([1, 2, 4, 5]) list([3, 5, 6]) list([2, 1, 5])]
1
(3,)
object


# Creating ndarrays

In [47]:
# array k andar same data type hongi
# list k andar ham 1 say zyada data type use kar saktay hain
a = [1,2,3]
print(type(a))

a = np.array(a)
print(a.dtype)

<class 'list'>
int32


In [48]:
a = (1,2,3)
print(type(a))

a = np.array(a)
type(a)

<class 'tuple'>


numpy.ndarray

In [49]:
a = {1,2,3}
print(type(a))

a = np.array(a)
type(a)

<class 'set'>


numpy.ndarray

In [52]:
l = [1,2,3]
a = np.array(l)
b = np.array(a)
a is b

False

# npasarray

In [53]:
l = [1,2,3]
a = np.asarray(l)
b = np.asarray(a)
a is b

True