In [1]:
import numpy as np

# Linear Algebra

In [2]:
# in list when we slising the vakue can not update
l = [1,3,4,8,9]
l[:2] = 5

# but in numpy array that would be possible

TypeError: can only assign an iterable

In [8]:
# slicing in different ways
a = np.arange(3 * 4).reshape((3, 4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
print(a[:2])

[[0 1 2 3]
 [4 5 6 7]]


In [10]:
print(a[0:2])

[[0 1 2 3]
 [4 5 6 7]]


In [11]:
print(a[-3:2])

[[0 1 2 3]
 [4 5 6 7]]


In [12]:
print(a[-3:-1])

[[0 1 2 3]
 [4 5 6 7]]


In [13]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [15]:
data = np.random.randn(7, 4)
data

array([[-0.12886631, -0.18046115,  0.64687192,  1.21382842],
       [ 0.87705826,  0.652897  , -0.87332943,  0.64721888],
       [-0.2071349 ,  1.417329  ,  0.2646154 , -0.50392497],
       [-1.23639032, -0.79608545, -0.43567882,  0.21853475],
       [-0.83031037,  2.43603101, -0.07335672,  0.42472213],
       [-1.27217675, -1.09880081, -1.3901101 ,  0.378878  ],
       [-1.12740546, -0.22002107,  2.31568793, -0.65604101]])

In [ ]:
data[[True, False, False, True, False, False, False]]

In [16]:
data[names == 'Bob']

array([[-0.12886631, -0.18046115,  0.64687192,  1.21382842],
       [-1.23639032, -0.79608545, -0.43567882,  0.21853475]])

In [18]:
data[(names == 'Bob') | (names == 'Will')]

array([[-0.12886631, -0.18046115,  0.64687192,  1.21382842],
       [-0.2071349 ,  1.417329  ,  0.2646154 , -0.50392497],
       [-1.23639032, -0.79608545, -0.43567882,  0.21853475],
       [-0.83031037,  2.43603101, -0.07335672,  0.42472213]])

In [19]:
data[(names == 'Bob') | (names == 'Will')][:,[0,-1]]

array([[-0.12886631,  1.21382842],
       [-0.2071349 , -0.50392497],
       [-1.23639032,  0.21853475],
       [-0.83031037,  0.42472213]])

In [20]:
# ~ mean not equal
# print all data skip 'Bob'
data[~(names == 'Bob')]

array([[ 0.87705826,  0.652897  , -0.87332943,  0.64721888],
       [-0.2071349 ,  1.417329  ,  0.2646154 , -0.50392497],
       [-0.83031037,  2.43603101, -0.07335672,  0.42472213],
       [-1.27217675, -1.09880081, -1.3901101 ,  0.378878  ],
       [-1.12740546, -0.22002107,  2.31568793, -0.65604101]])

In [21]:
print(data)

[[-0.12886631 -0.18046115  0.64687192  1.21382842]
 [ 0.87705826  0.652897   -0.87332943  0.64721888]
 [-0.2071349   1.417329    0.2646154  -0.50392497]
 [-1.23639032 -0.79608545 -0.43567882  0.21853475]
 [-0.83031037  2.43603101 -0.07335672  0.42472213]
 [-1.27217675 -1.09880081 -1.3901101   0.378878  ]
 [-1.12740546 -0.22002107  2.31568793 -0.65604101]]


In [22]:
print(data)
data[[0]]

[[-0.12886631 -0.18046115  0.64687192  1.21382842]
 [ 0.87705826  0.652897   -0.87332943  0.64721888]
 [-0.2071349   1.417329    0.2646154  -0.50392497]
 [-1.23639032 -0.79608545 -0.43567882  0.21853475]
 [-0.83031037  2.43603101 -0.07335672  0.42472213]
 [-1.27217675 -1.09880081 -1.3901101   0.378878  ]
 [-1.12740546 -0.22002107  2.31568793 -0.65604101]]


array([[-0.12886631, -0.18046115,  0.64687192,  1.21382842]])

In [23]:
print(data)
data[[0, -1]]

[[-0.12886631 -0.18046115  0.64687192  1.21382842]
 [ 0.87705826  0.652897   -0.87332943  0.64721888]
 [-0.2071349   1.417329    0.2646154  -0.50392497]
 [-1.23639032 -0.79608545 -0.43567882  0.21853475]
 [-0.83031037  2.43603101 -0.07335672  0.42472213]
 [-1.27217675 -1.09880081 -1.3901101   0.378878  ]
 [-1.12740546 -0.22002107  2.31568793 -0.65604101]]


array([[-0.12886631, -0.18046115,  0.64687192,  1.21382842],
       [-1.12740546, -0.22002107,  2.31568793, -0.65604101]])

In [24]:
print(data) # arr[[rows], [columns]]
data[[0, -1, 3]]

[[-0.12886631 -0.18046115  0.64687192  1.21382842]
 [ 0.87705826  0.652897   -0.87332943  0.64721888]
 [-0.2071349   1.417329    0.2646154  -0.50392497]
 [-1.23639032 -0.79608545 -0.43567882  0.21853475]
 [-0.83031037  2.43603101 -0.07335672  0.42472213]
 [-1.27217675 -1.09880081 -1.3901101   0.378878  ]
 [-1.12740546 -0.22002107  2.31568793 -0.65604101]]


array([[-0.12886631, -0.18046115,  0.64687192,  1.21382842],
       [-1.12740546, -0.22002107,  2.31568793, -0.65604101],
       [-1.23639032, -0.79608545, -0.43567882,  0.21853475]])

In [26]:
print(data)
data[:, [0 -1]]

[[-0.12886631 -0.18046115  0.64687192  1.21382842]
 [ 0.87705826  0.652897   -0.87332943  0.64721888]
 [-0.2071349   1.417329    0.2646154  -0.50392497]
 [-1.23639032 -0.79608545 -0.43567882  0.21853475]
 [-0.83031037  2.43603101 -0.07335672  0.42472213]
 [-1.27217675 -1.09880081 -1.3901101   0.378878  ]
 [-1.12740546 -0.22002107  2.31568793 -0.65604101]]


array([[ 1.21382842],
       [ 0.64721888],
       [-0.50392497],
       [ 0.21853475],
       [ 0.42472213],
       [ 0.378878  ],
       [-0.65604101]])

In [27]:
data < 0

array([[ True,  True, False, False],
       [False, False,  True, False],
       [ True, False, False,  True],
       [ True,  True,  True, False],
       [ True, False,  True, False],
       [ True,  True,  True, False],
       [ True,  True, False,  True]])

In [28]:
data[data < 0]
data

array([[-0.12886631, -0.18046115,  0.64687192,  1.21382842],
       [ 0.87705826,  0.652897  , -0.87332943,  0.64721888],
       [-0.2071349 ,  1.417329  ,  0.2646154 , -0.50392497],
       [-1.23639032, -0.79608545, -0.43567882,  0.21853475],
       [-0.83031037,  2.43603101, -0.07335672,  0.42472213],
       [-1.27217675, -1.09880081, -1.3901101 ,  0.378878  ],
       [-1.12740546, -0.22002107,  2.31568793, -0.65604101]])

In [29]:
data[data < 0] = 0
data

array([[0.        , 0.        , 0.64687192, 1.21382842],
       [0.87705826, 0.652897  , 0.        , 0.64721888],
       [0.        , 1.417329  , 0.2646154 , 0.        ],
       [0.        , 0.        , 0.        , 0.21853475],
       [0.        , 2.43603101, 0.        , 0.42472213],
       [0.        , 0.        , 0.        , 0.378878  ],
       [0.        , 0.        , 2.31568793, 0.        ]])

# Fancy Slicing

In [30]:
print(data)

[[0.         0.         0.64687192 1.21382842]
 [0.87705826 0.652897   0.         0.64721888]
 [0.         1.417329   0.2646154  0.        ]
 [0.         0.         0.         0.21853475]
 [0.         2.43603101 0.         0.42472213]
 [0.         0.         0.         0.378878  ]
 [0.         0.         2.31568793 0.        ]]


In [31]:
# fancy slicing
print(data[:, [-2, 0, -1]])

[[0.64687192 0.         1.21382842]
 [0.         0.87705826 0.64721888]
 [0.2646154  0.         0.        ]
 [0.         0.         0.21853475]
 [0.         0.         0.42472213]
 [0.         0.         0.378878  ]
 [2.31568793 0.         0.        ]]


In [33]:
print(data[:, 1])

[0.         0.652897   1.417329   0.         2.43603101 0.
 0.        ]


In [35]:
print(data[:, 1:][:, [-1, 2, 1]])

[[1.21382842 1.21382842 0.64687192]
 [0.64721888 0.64721888 0.        ]
 [0.         0.         0.2646154 ]
 [0.21853475 0.21853475 0.        ]
 [0.42472213 0.42472213 0.        ]
 [0.378878   0.378878   0.        ]
 [0.         0.         2.31568793]]


In [36]:
a = np.zeros((8, 4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [37]:
a = np.zeros((8, 4))
print(a)

for i, v in enumerate(a):
    a[i] = i

a

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [38]:
a = np.zeros((8, 4))
print(a)

for i in range(len(a)):
    a[i] = i

a

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [40]:
a = np.zeros((8, 4))
print(a)

for i in (a.shape):
    a[i] = i

a

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


IndexError: index 8 is out of bounds for axis 0 with size 8

In [41]:
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [42]:
print(a)
print()
print(a.T)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [43]:
print(a)
print()
print(a.T) # attribute
print()
print(a.transpose()) # methode because use ()

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [45]:
a = np.array([[1, 2],
             [3, 4]])
b = np.array([[5, 6],
             [7, 8]])
print(a,b , sep = "\n\n")

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]


In [47]:
a = np.array([[1, 2],
             [3, 4]])
b = np.array([[5, 6],
             [7, 8]])

print(a,b , sep = "\n\n")
print()
print(a * b)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[ 5 12]
 [21 32]]


In [48]:
# take dot product
print(a @ b)

[[19 22]
 [43 50]]


In [49]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [50]:
arr = np.arange(2*2*4).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [52]:
arr.transpose()

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [53]:
arr = np.arange(10, 2*2*4+10).reshape((2, 2, 4))
arr

array([[[10, 11, 12, 13],
        [14, 15, 16, 17]],

       [[18, 19, 20, 21],
        [22, 23, 24, 25]]])

In [54]:
print(arr)
arr.transpose((1, 0, 2))

[[[10 11 12 13]
  [14 15 16 17]]

 [[18 19 20 21]
  [22 23 24 25]]]


array([[[10, 11, 12, 13],
        [18, 19, 20, 21]],

       [[14, 15, 16, 17],
        [22, 23, 24, 25]]])

In [55]:
# help
arr.transpose??

In [56]:
print(arr)
arr.transpose((2, 1, 0))

[[[10 11 12 13]
  [14 15 16 17]]

 [[18 19 20 21]
  [22 23 24 25]]]


array([[[10, 18],
        [14, 22]],

       [[11, 19],
        [15, 23]],

       [[12, 20],
        [16, 24]],

       [[13, 21],
        [17, 25]]])

In [58]:
print(arr)
arr.transpose((1, 2, 0))

[[[10 11 12 13]
  [14 15 16 17]]

 [[18 19 20 21]
  [22 23 24 25]]]


array([[[10, 18],
        [11, 19],
        [12, 20],
        [13, 21]],

       [[14, 22],
        [15, 23],
        [16, 24],
        [17, 25]]])

In [59]:
print(arr)
arr.swapaxes(1, 2)

[[[10 11 12 13]
  [14 15 16 17]]

 [[18 19 20 21]
  [22 23 24 25]]]


array([[[10, 14],
        [11, 15],
        [12, 16],
        [13, 17]],

       [[18, 22],
        [19, 23],
        [20, 24],
        [21, 25]]])

In [60]:
print(arr)
arr.swapaxes(2, 1)

[[[10 11 12 13]
  [14 15 16 17]]

 [[18 19 20 21]
  [22 23 24 25]]]


array([[[10, 14],
        [11, 15],
        [12, 16],
        [13, 17]],

       [[18, 22],
        [19, 23],
        [20, 24],
        [21, 25]]])

In [61]:
print(arr)
arr.swapaxes(1, 1)

[[[10 11 12 13]
  [14 15 16 17]]

 [[18 19 20 21]
  [22 23 24 25]]]


array([[[10, 11, 12, 13],
        [14, 15, 16, 17]],

       [[18, 19, 20, 21],
        [22, 23, 24, 25]]])

In [62]:
print(arr)
arr.swapaxes(2, 2)

[[[10 11 12 13]
  [14 15 16 17]]

 [[18 19 20 21]
  [22 23 24 25]]]


array([[[10, 11, 12, 13],
        [14, 15, 16, 17]],

       [[18, 19, 20, 21],
        [22, 23, 24, 25]]])

In [63]:
print(arr)
arr.swapaxes(0, 2)

[[[10 11 12 13]
  [14 15 16 17]]

 [[18 19 20 21]
  [22 23 24 25]]]


array([[[10, 18],
        [14, 22]],

       [[11, 19],
        [15, 23]],

       [[12, 20],
        [16, 24]],

       [[13, 21],
        [17, 25]]])

In [64]:
print(arr)
arr.swapaxes(1, 0)

[[[10 11 12 13]
  [14 15 16 17]]

 [[18 19 20 21]
  [22 23 24 25]]]


array([[[10, 11, 12, 13],
        [18, 19, 20, 21]],

       [[14, 15, 16, 17],
        [22, 23, 24, 25]]])

In [65]:
a = np.arange(3*4).reshape((3,4))
print(a)

a.swapaxes(1, 0)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [67]:
a = np.arange(3*4).reshape((3,4))
print(a)

a.transpose(1, 0)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

# Universal Functions: Fast Element Wise Function

In [68]:
a = np.array([1,2,-3,4,-5,7,-9])

# abs print absolute value
print(np.abs(a))

[1 2 3 4 5 7 9]


In [69]:
a = np.array([1,2,-3,4,-5,7,-9])

# fabs print float value
print(np.fabs(a))

[1. 2. 3. 4. 5. 7. 9.]


In [70]:
a = np.array([1,2,-3,4,-5,7,-9])

print(np.sqrt(a))

[1.         1.41421356        nan 2.                nan 2.64575131
        nan]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until


In [71]:
a = np.array([1,2,-3,4,-5,7,-9])

print(np.square(a))

[ 1  4  9 16 25 49 81]


In [72]:
a = np.array([1,2,-3,4,-5,7,-9])
# exp take exponent
print(np.exp(a))

[2.71828183e+00 7.38905610e+00 4.97870684e-02 5.45981500e+01
 6.73794700e-03 1.09663316e+03 1.23409804e-04]


In [73]:
a = np.array([1,2,-3,4,-5,7,-9])

print(np.log(a))

[0.         0.69314718        nan 1.38629436        nan 1.94591015
        nan]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in log
  This is separate from the ipykernel package so we can avoid doing imports until


In [74]:
a = np.array([1,2,-3,4,-5,7,-9])

print(np.log10(a))

[0.         0.30103           nan 0.60205999        nan 0.84509804
        nan]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in log10
  This is separate from the ipykernel package so we can avoid doing imports until


In [75]:
a = np.array([1,2,-3,4,-5,7,-9])

print(np.log2(a))

[0.         1.                nan 2.                nan 2.80735492
        nan]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in log2
  This is separate from the ipykernel package so we can avoid doing imports until


In [77]:
a = np.array([1,2,-3,4,-5,7,-9])

print(np.log1p(a))

[0.69314718 1.09861229        nan 1.60943791        nan 2.07944154
        nan]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in log1p
  This is separate from the ipykernel package so we can avoid doing imports until


In [78]:
a = np.array([1,2,-3,4,-5,7,-9])

print(np.sign(a))

[ 1  1 -1  1 -1  1 -1]


In [79]:
a = np.array([1,2,-3,4,-5,7,-9])

print(np.ceil(a))

[ 1.  2. -3.  4. -5.  7. -9.]


In [80]:
a = np.array([1,2,-3,4,-5,7,-9])

print(np.floor(a))

[ 1.  2. -3.  4. -5.  7. -9.]


In [81]:
a = np.array([1,2,-3,4,-5,7,-9])

print(np.rint(a))

[ 1.  2. -3.  4. -5.  7. -9.]


In [82]:
a = np.array([1,2,-3,4,-5,7,-9])

print(np.modf(a))

(array([ 0.,  0., -0.,  0., -0.,  0., -0.]), array([ 1.,  2., -3.,  4., -5.,  7., -9.]))


In [83]:
a = np.array([1,2,-3,4,-5,7,-9])

print(np.isnan(a))

[False False False False False False False]


In [85]:
a = np.array([1.27,3.9,9.2])
w, f = np.modf(a)

print(w, f, sep = "\n")

[0.27 0.9  0.2 ]
[1. 3. 9.]


In [89]:
a = np.array([11,20,25])
np.fmod(a, 3)

array([2, 2, 1], dtype=int32)

In [90]:
a = np.array([1,2,-3,4,-5,7,-9])

print(np.isfinite(a))

[ True  True  True  True  True  True  True]


In [91]:
a = np.array([1,2,-3,4,-5,7,-9])

print(np.isinf(a))

[False False False False False False False]


In [93]:
a = np.array([1,2,3])
b = np.array([-1,5,7])

np.maximum(a,b)

array([1, 5, 7])

In [94]:
a = np.array([1,2,3])
b = np.array([-1,5,7])

np.minimum(a,b)

array([-1,  2,  3])

In [95]:
a = np.array([1,2,3])
b = np.array([-1,5,7])

np.fmax(a,b)

array([1, 5, 7])

In [96]:
a = np.array([1,2,3])
b = np.array([-1,5,7])

np.fmin(a,b)

array([-1,  2,  3])

# Array-Oriented Programming With Arays

In [99]:
a = np.arange(3*2).reshape((3,2))
print(a)

print(np.meshgrid(a,a))

[[0 1]
 [2 3]
 [4 5]]
[array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]]), array([[0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5]])]


In [100]:
a = np.arange(36)
a % 3 == 0

array([ True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False])

In [101]:
a = np.arange(36)
#np.where(condition, true_value, false_value)

np.where(a % 3, "yes", "no")

array(['no', 'yes', 'yes', 'no', 'yes', 'yes', 'no', 'yes', 'yes', 'no',
       'yes', 'yes', 'no', 'yes', 'yes', 'no', 'yes', 'yes', 'no', 'yes',
       'yes', 'no', 'yes', 'yes', 'no', 'yes', 'yes', 'no', 'yes', 'yes',
       'no', 'yes', 'yes', 'no', 'yes', 'yes'], dtype='<U3')

# Mathematical And Statistical Methods

In [102]:
a = np.arange(3*4).reshape((3,4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [103]:
np.sum(a)

66

In [104]:
a = np.arange(3*4).reshape((3,4))
print(a)

np.sum(a, axis = 0)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([12, 15, 18, 21])

In [105]:
a = np.arange(3*4).reshape((3,4))
print(a)

np.sum(a, axis = 1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 6, 22, 38])

In [106]:
a.mean()

5.5

In [107]:
np.mean(a)

5.5

In [108]:
a.mean(axis = 1)

array([1.5, 5.5, 9.5])

In [109]:
a.mean(axis = 0)

array([4., 5., 6., 7.])

In [110]:
a.cumsum(axis = 1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [111]:
a.cumsum(axis = 0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]], dtype=int32)

In [112]:
a.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66], dtype=int32)

In [113]:
a.std(axis = 1)

array([1.11803399, 1.11803399, 1.11803399])

In [114]:
a.var()

11.916666666666666

In [115]:
a.std()

3.452052529534663

In [116]:
a.min()

0

In [117]:
a.max()

11

In [118]:
# show minimum value index
a.argmin()

0

In [119]:
# show large value index
a.argmax()

11

In [121]:
np.argsort(a)

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]], dtype=int64)