In [1]:
import numpy as np

In [2]:
x = np.zeros((4,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [4]:
np.empty((7,7))

array([[5.79014622e-312, 5.79008526e-312, 1.68821038e+195,
        1.49003499e+195, 5.70932366e+228, 4.76659976e+180,
        4.65688237e+164],
       [8.78422036e+247, 2.19529495e-152, 7.49363265e+247,
        2.39294633e-258, 6.07886271e+247, 3.93501887e+024,
        2.52301636e-258],
       [4.47593816e-091, 5.28595595e-085, 5.98115753e-114,
        1.28822630e-057, 8.44250580e-053, 9.08967386e+242,
        1.05135744e-153],
       [2.65862877e-260, 8.39459671e+217, 4.41496367e+222,
        3.02012407e-110, 1.05191453e-153, 9.66890684e+242,
        9.78375159e+199],
       [4.83245960e+276, 9.91598802e-096, 1.15296929e-259,
        8.94213159e+130, 4.56340382e-072, 7.57854830e-010,
        6.98028752e+199],
       [3.92675050e+223, 6.98387920e-077, 5.04050503e+223,
        3.74165235e+233, 3.74165281e+233, 2.87350346e+159,
        2.13389712e+161],
       [1.06024692e-153, 6.99416121e-009, 7.35280766e+223,
        3.74795232e+233, 2.84845496e-110, 1.39284475e-309,
        1.00477541

In [5]:
l = [1,4,5,7]

In [6]:
np.array(l)

array([1, 4, 5, 7])

In [7]:
# arange is the Method of numpy
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [8]:
x.shape

(4, 4)

In [9]:
x = np.arange(1,100,10)
x

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [10]:
x.shape

(10,)

In [11]:
x = np.zeros((10,10))

In [12]:
x.shape

(10, 10)

In [13]:
y = x.reshape((2,2,5,5))
y

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [14]:
# Check data type
y.dtype

dtype('float64')

In [15]:
# check Dimension
y.ndim

4