In [1]:
import numpy as np

In [4]:
a = np.arange(1, 28).reshape((3,3,3))
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [8]:
a.shape

(3, 3, 3)

In [9]:
# Shape is a inmemory operation perform
# inmemory mean change real value
a.shape = (3, 9)
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [11]:
# in this we mension dimensions
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [12]:
# in this create a copy and save it but not change real value
np.zeros_like(a)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [13]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [14]:
np.ones_like(a)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [15]:
np.empty((2,2,2))

array([[[0.00e+000, 0.00e+000],
        [0.00e+000, 0.00e+000]],

       [[0.00e+000, 4.37e-321],
        [0.00e+000, 0.00e+000]]])

In [16]:
np.empty_like(a)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [17]:
np.full((2,3,3), fill_value = 5)

array([[[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]]])

In [18]:
np.full_like(a, 7)

array([[7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7]])

In [19]:
np.ones((2,3)) * 7

array([[7., 7., 7.],
       [7., 7., 7.]])

In [20]:
np.ones_like(a, dtype = np.float64)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [24]:
# array function convert in array and create a copy
# asarray can't create copy
np.array(15)

array(15)

In [26]:
np.eye??

In [27]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [28]:
np.identity??

# Data Types For ndarray

In [30]:
a = np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [31]:
# astype as a function
# dtype is a attribute
a = np.arange(1,13).astype(np.float64).reshape((3,4))
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [32]:
a = np.arange(1,13).reshape((3,4)).astype(np.float64)
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [34]:
a = np.arange(1,13).reshape((3,4)).astype(np.character)
a

array([[b'1', b'2', b'3', b'4'],
       [b'5', b'6', b'7', b'8'],
       [b'9', b'10', b'11', b'12']], dtype='|S11')

In [33]:
a = np.arange(1,13, dtype = "float").reshape((3,4))
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [38]:
arr2 = np.array([1,2,3], dtype = np.int32)
arr2

array([1, 2, 3])

In [40]:
print(a.dtype)

|S11


In [41]:
print(arr2.dtype)

int32


In [43]:
print(type(a))

<class 'numpy.ndarray'>


In [44]:
# int typs
a = np.array([1,2,3], dtype = 'int')
print(a.dtype)

a = np.array([1,2,3], dtype = np.int64)
print(a.dtype)

a = np.array([1,2,3], dtype = 'i8')
print(a.dtype)

a = np.array([1,2,3], dtype = 'u8')
print(a.dtype)

int32
int64
int64
uint64


In [47]:
# float typs
a = np.array([1,2,3], dtype = 'f')
print(a.dtype)

a = np.array([1,2,3], dtype = 'd')
print(a.dtype)

a = np.array([1,2,3], dtype = 'f2')
print(a.dtype)

float32
float64
float16


In [51]:
# create regular expression
def abc(x):
    try:
        x = str(x)
        return np.int64("".join([i for i in x if str.isnumeric(i)]))
    except:
        return 0
abc("sjdbjaskbjksabfkjsabjkas")

0

In [53]:
a = np.arange(1,13, dtype = np.float64)
b = np.arange(1, 4)
print(a.dtype)
print(b.dtype)

float64
int32


In [54]:
b.astype(a.dtype)

array([1., 2., 3.])

In [55]:
a = np.arange(1, 28).reshape((3,3,3))
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [56]:
# condition those value divided by 5
a % 5 == 0

array([[[False, False, False],
        [False,  True, False],
        [False, False, False]],

       [[ True, False, False],
        [False, False,  True],
        [False, False, False]],

       [[False,  True, False],
        [False, False, False],
        [ True, False, False]]])

In [57]:
a[a % 5 == 0]

array([ 5, 10, 15, 20, 25])

In [58]:
a[(a % 5 == 0) & (a % 3 ==  0)]

array([15])

In [59]:
# slicing
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [60]:
# slicing
a[1]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [61]:
# slicing
a[1][1]

array([13, 14, 15])

In [62]:
# slicing
a[1][1][1]

14

In [63]:
# slicing
a[1:]

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [64]:
# slicing
a[1:, 1:, :1]

array([[[13],
        [16]],

       [[22],
        [25]]])

In [67]:
a[1:,1:,:1]

array([[[13],
        [16]],

       [[22],
        [25]]])

In [68]:
# slicing
a[1:][1:][1:]

array([], shape=(0, 3, 3), dtype=int32)

In [70]:
# slicing
a[1:][1:]

array([[[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [71]:
# slicing
a[1:][1:][1:]

array([], shape=(0, 3, 3), dtype=int32)