In [1]:
import numpy as np

In [3]:
# randint fix low and high value and set size
a = np.random.randint(1, 20, size = 20)
b = np.random.randint(1, 10, size = 10)
print(a, b, sep = "\n\n")

[ 3 15  1 10 12 15 11  3 14 18 15 12  4  1  6 19 10  7 12  2]

[5 4 5 2 5 5 1 2 9 7]


In [5]:
# match value using python
[True if x in a else False for x in b]

[False, True, False, True, False, False, True, True, False, True]

In [9]:
# using numpy find b in a using np1d
np.in1d(b , a)

array([False,  True, False,  True, False, False,  True,  True, False,
        True])

# Staking

In [10]:
a = np.arange(1, 11)
b = a * 3
print(a, b, sep = "\n\n")

[ 1  2  3  4  5  6  7  8  9 10]

[ 3  6  9 12 15 18 21 24 27 30]


In [11]:
a = np.arange(1, 11)
b = a * 3
print(a, b, sep = "\n\n")

np.stack((a, b), axis = 0)

[ 1  2  3  4  5  6  7  8  9 10]

[ 3  6  9 12 15 18 21 24 27 30]


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30]])

In [12]:
a = np.arange(1, 11)
b = a * 3
print(a, b, sep = "\n\n")

np.stack((a, b), axis = 1)

[ 1  2  3  4  5  6  7  8  9 10]

[ 3  6  9 12 15 18 21 24 27 30]


array([[ 1,  3],
       [ 2,  6],
       [ 3,  9],
       [ 4, 12],
       [ 5, 15],
       [ 6, 18],
       [ 7, 21],
       [ 8, 24],
       [ 9, 27],
       [10, 30]])

In [13]:
a = np.arange(1, 11)
b = a * 3
print(a, b, sep = "\n\n")

np.hstack((a, b))

[ 1  2  3  4  5  6  7  8  9 10]

[ 3  6  9 12 15 18 21 24 27 30]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  3,  6,  9, 12, 15, 18, 21,
       24, 27, 30])

In [14]:
a = np.arange(1, 11)
b = a * 3
print(a, b, sep = "\n\n")

np.vstack((a, b))

[ 1  2  3  4  5  6  7  8  9 10]

[ 3  6  9 12 15 18 21 24 27 30]


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30]])

In [15]:
a = np.arange(2 * 2 * 2).reshape((2, 2, 2))
b = a + 10
print(a, b, sep = "\n\n")

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

[[[10 11]
  [12 13]]

 [[14 15]
  [16 17]]]


In [17]:
np.dstack((a, b))

array([[[ 0,  1, 10, 11],
        [ 2,  3, 12, 13]],

       [[ 4,  5, 14, 15],
        [ 6,  7, 16, 17]]])

In [18]:
a = np.arange(2 * 2).reshape(2, 2)
print(a)
a + 5

[[0 1]
 [2 3]]


array([[5, 6],
       [7, 8]])

In [19]:
b = np.full_like(a, 5)
print(a, b, sep = "\n\n")

[[0 1]
 [2 3]]

[[5 5]
 [5 5]]


In [20]:
a + b

array([[5, 6],
       [7, 8]])

In [21]:
a = np.arange(1, 11)
b = a * 3
print(a, b, sep = "\n\n")
np.column_stack((a, b))

[ 1  2  3  4  5  6  7  8  9 10]

[ 3  6  9 12 15 18 21 24 27 30]


array([[ 1,  3],
       [ 2,  6],
       [ 3,  9],
       [ 4, 12],
       [ 5, 15],
       [ 6, 18],
       [ 7, 21],
       [ 8, 24],
       [ 9, 27],
       [10, 30]])

In [22]:
a = np.arange(1, 11)
b = a * 3
print(a, b, sep = "\n\n")
np.row_stack((a, b))

[ 1  2  3  4  5  6  7  8  9 10]

[ 3  6  9 12 15 18 21 24 27 30]


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30]])

In [24]:
a = np.random.randn(6, 5)
a

array([[ 1.48460849,  0.2165296 ,  0.87771379, -0.54340258, -1.22552134],
       [ 0.22284683,  0.48234518,  1.60599874,  0.08038072,  0.88792193],
       [ 1.36837569, -0.47951549, -1.11128452, -0.5992606 , -0.02388098],
       [-0.19326049, -0.21494348,  0.71854324, -0.61324241, -0.26817243],
       [-1.25078186,  0.77526253, -0.55979381, -0.28523076, -0.33297698],
       [ 0.2791004 ,  0.34889842, -0.03187326, -0.68135727,  0.34168595]])

In [25]:
# break matrics using split
a = np.arange(6 * 5).reshape((6, 5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [26]:
print(a)
np.split(a, 3)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]])]

In [27]:
print(a)
np.split(a, 2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


[array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]])]

In [32]:
print(a)
np.split(a, 2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


[array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]])]

In [38]:
# randint fix low and high value and set size
a = np.random.randint(1, 20, size = 20)
b = np.random.randint(1, 10, size = 10)
print(a, b, sep = "\n\n")

np.intersect1d(a, b)

[14 18 18 19 13  9 14 17 14 17  3  8 13 10  6  4  4  6  4 17]

[8 5 3 6 1 7 1 3 8 4]


array([3, 4, 6, 8])

In [39]:
# randint fix low and high value and set size
a = np.random.randint(1, 20, size = 20)
b = np.random.randint(1, 10, size = 10)
print(a, b, sep = "\n\n")

np.union1d(a, b)

[ 2  2 11 17 10 15 19  4 13 18  1 11 12 15  4 12 16  4 16 18]

[1 6 6 9 9 5 2 4 7 4]


array([ 1,  2,  4,  5,  6,  7,  9, 10, 11, 12, 13, 15, 16, 17, 18, 19])

In [40]:
# randint fix low and high value and set size
a = np.random.randint(1, 20, size = 20)
b = np.random.randint(1, 10, size = 10)
print(a, b, sep = "\n\n")

np.setdiff1d(a, b)

[ 8 10  9 13  6  2 18 19  7  9  9  8 14 19 12  5 19 12 13  7]

[2 2 2 1 6 3 8 4 2 9]


array([ 5,  7, 10, 12, 13, 14, 18, 19])

In [41]:
# randint fix low and high value and set size
a = np.random.randint(1, 20, size = 20)
b = np.random.randint(1, 10, size = 10)
print(a, b, sep = "\n\n")

np.setxor1d(a, b)

[14 15  6  6  3  5 18 12  7 19  5 15 17 13 15 10 19 13  1 11]

[7 9 3 6 3 3 5 4 4 8]


array([ 1,  4,  8,  9, 10, 11, 12, 13, 14, 15, 17, 18, 19])

In [42]:
np.setxor1d(a, b)
# create truth table
# 0 0 - 0
# 1 0 - 1
# 0 1 - 1
# 1 1 - 0

array([ 1,  4,  8,  9, 10, 11, 12, 13, 14, 15, 17, 18, 19])