In [1]:
import numpy as np

In [2]:
# create 4 by 5 array
x = np.random.randn(4,5)
x

array([[-1.00457765,  0.64840426, -0.01249234, -0.91908869, -1.80416875],
       [-0.74701292,  1.02821182, -1.63043528,  1.51895858,  0.37032761],
       [ 1.76488433,  0.39637097,  0.44189838,  0.66212968,  1.80096762],
       [ 0.92879312,  0.54338013,  1.06918668,  0.11266993, -0.08472738]])

In [3]:
# Reshape array 1st dimension 2, 2nd dimension 2, 3rd dimension 5
# By default show row major order
x.reshape((2,2,5))

array([[[-1.00457765,  0.64840426, -0.01249234, -0.91908869,
         -1.80416875],
        [-0.74701292,  1.02821182, -1.63043528,  1.51895858,
          0.37032761]],

       [[ 1.76488433,  0.39637097,  0.44189838,  0.66212968,
          1.80096762],
        [ 0.92879312,  0.54338013,  1.06918668,  0.11266993,
         -0.08472738]]])

In [4]:
# Reshape column major order
x.reshape((2,2,5), order = 'F')

array([[[-1.00457765,  0.64840426, -0.01249234, -0.91908869,
         -1.80416875],
        [ 1.76488433,  0.39637097,  0.44189838,  0.66212968,
          1.80096762]],

       [[-0.74701292,  1.02821182, -1.63043528,  1.51895858,
          0.37032761],
        [ 0.92879312,  0.54338013,  1.06918668,  0.11266993,
         -0.08472738]]])

In [5]:
# Reshape array and skip 1 dimention
x.reshape((2,2,-1))

array([[[-1.00457765,  0.64840426, -0.01249234, -0.91908869,
         -1.80416875],
        [-0.74701292,  1.02821182, -1.63043528,  1.51895858,
          0.37032761]],

       [[ 1.76488433,  0.39637097,  0.44189838,  0.66212968,
          1.80096762],
        [ 0.92879312,  0.54338013,  1.06918668,  0.11266993,
         -0.08472738]]])

In [6]:
x

array([[-1.00457765,  0.64840426, -0.01249234, -0.91908869, -1.80416875],
       [-0.74701292,  1.02821182, -1.63043528,  1.51895858,  0.37032761],
       [ 1.76488433,  0.39637097,  0.44189838,  0.66212968,  1.80096762],
       [ 0.92879312,  0.54338013,  1.06918668,  0.11266993, -0.08472738]])

In [7]:
# convert array x in 1 dimention array
x.ravel()

array([-1.00457765,  0.64840426, -0.01249234, -0.91908869, -1.80416875,
       -0.74701292,  1.02821182, -1.63043528,  1.51895858,  0.37032761,
        1.76488433,  0.39637097,  0.44189838,  0.66212968,  1.80096762,
        0.92879312,  0.54338013,  1.06918668,  0.11266993, -0.08472738])

In [8]:
# convert array x in 1 dimention array
x.flatten()

array([-1.00457765,  0.64840426, -0.01249234, -0.91908869, -1.80416875,
       -0.74701292,  1.02821182, -1.63043528,  1.51895858,  0.37032761,
        1.76488433,  0.39637097,  0.44189838,  0.66212968,  1.80096762,
        0.92879312,  0.54338013,  1.06918668,  0.11266993, -0.08472738])